spring.application.name=agendo

# ==========================================
# CONFIGURAÇÕES DE BANCO DE DADOS
# ==========================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agendo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

# ==========================================
# JPA / HIBERNATE E FLYWAY
# ==========================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# DESATIVA a criação automática do JPA, pois o Flyway fará isso!
spring.jpa.generate-ddl=false
# Altera de 'update' para 'validate' (O Hibernate só confere se a tabela existe)
spring.jpa.hibernate.ddl-auto=validate

# Ativa as Migrations
spring.flyway.enabled=true

# ==========================================
# CONFIGURAÇÕES DE E-MAIL
# ==========================================
# Se as variáveis de produção falharem, ele tenta usar o Mailtrap por padrão
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# CONFIGURAÇÕES DE SEGURANÇA E AMBIENTE
# ==========================================
jwt.secret=${SECRET_KEY:minha_chave_secreta_para_assinar_tokens}
app.frontend.url=${FRONTEND_URL:http://localhost:5173}