version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: agendo-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./project/agendo/backend 
      dockerfile: Dockerfile
    container_name: agendo-backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - SPRING_MAIL_HOST=${MAIL_HOST}
      - SPRING_MAIL_PORT=${MAIL_PORT}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./project/agendo/frontend 
      dockerfile: Dockerfile
      args:
        # Passa a URL do .env para o Dockerfile durante o build
        - VITE_API_URL=${VITE_API_URL}
    container_name: agendo-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: